FROM python:3.11-slim

WORKDIR /app

COPY requirements-sms.txt .
RUN pip install --no-cache-dir -r requirements-sms.txt

COPY app/core ./app/core
COPY app/sms ./app/sms

CMD ["celery", "-A", "app.sms.tasks.sms_tasks", "worker", "-Q", "sms_queue", "--loglevel=info"]