"""create email_templates table

Revision ID: 004
Revises: 003
Create Date: 2026-06-28 10:20:50.344728
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('template_id', sa.String(length=200), nullable=False),
    sa.Column('html_template_name', sa.String(length=100), nullable=False),
    sa.Column('variables_count', sa.Integer(), nullable=False),
    sa.Column('variables_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='{"buyer_name": "Name", "seller_name": "Name", ...}'),
    sa.Column('has_media', sa.Boolean(), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=True, comment='IMAGE | DOC | VIDEO — null when has_media=False'),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('table_map', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='["product_table": [["Product Name", Quantity]], "order_table": [["Order ID", "Amount"]], ...] - values are lists of lists'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_templates')
    # ### end Alembic commands ###
